services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: Password12!
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
volumes:
  postgres:
